### ISSUE TITLE
something wrong when build on Ubuntu 16.04

### ISSUE THREAD

**Issue by ZhuangTingT** [kmammou/v-hacd#150]
I have run `cmake -S . -B build -DCMAKE_BUILD_TYPE=Release`  successfully. 
but when I run `cmake --build build`, some error occurred like `array must be initialized with a brace-enclosed initializer`.
May you have any suggestion？
CMake: 3.13.1
OS: ubuntu 16.04
`
/v-hacd-master/app$ cmake --build build
Scanning dependencies of target TestVHACD
[ 16%] Building CXX object CMakeFiles/TestVHACD.dir/TestVHACD.cpp.o
In file included from /v-hacd-master/app/TestVHACD.cpp:17:0:
/v-hacd-master/app/../include/VHACD.h:1481:59: error: array must be initialized with a brace-enclosed initializer
     std::array<uint64_t, VHACD_GOOGOL_SIZE> m_mantissa{ 0 };
                                                           ^
/v-hacd-master/app/../include/VHACD.h: In constructor ‘VHACD::ConvexHullAABBTreeNode::ConvexHullAABBTreeNode(VHACD::ConvexHullAABBTreeNode*)’:
/v-hacd-master/app/../include/VHACD.h:2169:22: error: array must be initialized with a brace-enclosed initializer
     : m_parent(parent)
                      ^
In file included from /v-hacd-master/app/TestVHACD.cpp:17:0:
/v-hacd-master/app/../include/VHACD.h: In constructor ‘VHACD::Vector3<T>::Vector3() [with T = double]’:
/v-hacd-master/app/../include/VHACD.h:233:5: error: array must be initialized with a brace-enclosed initializer
     Vector3() = default;
     ^
In file included from /v-hacd-master/app/TestVHACD.cpp:17:0:
/v-hacd-master/app/../include/VHACD.h: In constructor ‘VHACD::ConvexHullAABBTreeNode::ConvexHullAABBTreeNode(VHACD::ConvexHullAABBTreeNode*)’:
/v-hacd-master/app/../include/VHACD.h:2169:22: note: synthesized method ‘VHACD::Vector3<T>::Vector3() [with T = double]’ first required here 
     : m_parent(parent)
                      ^
In file included from /v-hacd-master/app/TestVHACD.cpp:17:0:
/v-hacd-master/app/../include/VHACD.h: In member function ‘bool VHACD::VoxelHull::FindConcavity(uint32_t, uint32_t&)’:
/v-hacd-master/app/../include/VHACD.h:6458:37: error: array must be initialized with a brace-enclosed initializer
             VHACD::Vector3<int32_t> p1;
                                     ^
In file included from /v-hacd-master/app/TestVHACD.cpp:17:0:
/v-hacd-master/app/../include/VHACD.h: In constructor ‘VHACD::Vector3<T>::Vector3() [with T = int]’:
/v-hacd-master/app/../include/VHACD.h:233:5: error: array must be initialized with a brace-enclosed initializer
     Vector3() = default;
     ^
In file included from /v-hacd-master/app/TestVHACD.cpp:17:0:
/v-hacd-master/app/../include/VHACD.h: In member function ‘bool VHACD::VoxelHull::FindConcavity(uint32_t, uint32_t&)’:
/v-hacd-master/app/../include/VHACD.h:6458:37: note: synthesized method ‘VHACD::Vector3<T>::Vector3() [with T = int]’ first required here 
             VHACD::Vector3<int32_t> p1;
                                     ^
CMakeFiles/TestVHACD.dir/build.make:62: recipe for target 'CMakeFiles/TestVHACD.dir/TestVHACD.cpp.o' failed
make[2]: *** [CMakeFiles/TestVHACD.dir/TestVHACD.cpp.o] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/TestVHACD.dir/all' failed
make[1]: *** [CMakeFiles/TestVHACD.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by lym29** [comment]
Hi I met the exact same problem, have you found a way to solve it? Thx
